[build]
  command = "npx cross-env CI=false npm ci && npm --prefix functions install && npm run build"
  publish = "build"
[build.environment]
  NODE_VERSION = "20"
[functions]
  directory = "functions"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
